apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-backstage-service
  description: Test service for dual provider verification (GitHub)
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: platform-team
